package de.ostfalia.svm.trafficSign;

public enum Trafficsign {
	GESCHWINDIGKEITSBEGRENZUNG_20(0)
	, GESCHWINDIGKEITSBEGRENZUNG_30(1)
	, GESCHWINDIGKEITSBEGRENZUNG_50(2)
	, GESCHWINDIGKEITSBEGRENZUNG_60(3)
	, GESCHWINDIGKEITSBEGRENZUNG_70(4)
	, GESCHWINDIGKEITSBEGRENZUNG_80(5)
	, GESCHWINDIGKEITSBEGRENZUNG_80_ENDE(6)
	, GESCHWINDIGKEITSBEGRENZUNG_100(7)
	, GESCHWINDIGKEITSBEGRENZUNG_120(8)
	, UEBERHOLVERBOT(9)
	, UEBERHOLVERBOT_FUER_LKWS(10)
	, VORFAHRTSSCHILD_EINMALIG(11)
	, VORFAHRTSTRASSE(12)
	, VORFAHRTGEWAEHREN(13)
	, STOP(14)
	, VERBOT_FUER_ALLE_FAHRZEUGE(15)
	, VERBOT_FUER_LKWS(16)
	, VERBOT_DER_EINFAHRT(17)
	, GEFAHRENSTELLE(18)
	, KURVE_LINKS(19)
	, KURVE_RECHTS(20)
	, DOPPELKURVE_ERST_LINKS(21)
	, UNEBENE_FAHRBAHN(22)
	, SCHLEUDER_GEFAHR(23)
	, VERENGTE_FAHRBAHN_RECHTS(24)
	, ACHTUNG_BAUSTELLE(25)
	, ACHTUNG_AMPEL(26)
	, ACHTUNG_FUSSGAENGER(27)
	, ACHTUNG_KINDER(28)
	, ACHTUNG_FAHRRADFAHRER(29)
	, ACHTUNG_SCHNEE_ODER_GLAETTE(30)
	, ACHTUNG_WILDWECHSEL(31)
	, GESCHWINDIGKEITSBEGRENZUNG_ENDE(32)
	, VORGESCHRIEBENE_FAHRTRICHTUNG_RECHTS(33)
	, VORGESCHRIEBENE_FAHRTRICHTUNG_LINKS(34)
	, VORGESCHRIEBENE_FAHRTRICHTUNG_GERADEAUS(35)
	, VORGESCHRIEBENE_FAHRTRICHTUNG_GERADEAUS_RECHTS(36)
	, VORGESCHRIEBENE_FAHRTRICHTUNG_GERADEAUS_LINKS(37)
	, VORGESCHRIEBENE_VORBEIFAHRT_RECHTS(38)
	, VORGESCHRIEBENE_VORBEIFAHRT_LINKS(39)
	, KREISVERKEHR(40)
	, UEBERHOLVERBOT_ENDE(41)
	, UEBERHOLVERBOT_LKW_ENDE(42);
	
	private final int i;
	
	private Trafficsign(int i) {
		this.i = i;
	}
	
	public int getValue() {
		return i;
	}
	
	public static Trafficsign getByValue(int value) {
		Trafficsign[] values = values();
		for (Trafficsign trafficsign : values) {
			if(trafficsign.getValue() == value)
				return trafficsign;
		}
		return null;
	}
}
